### PR TITLE
Fix the PauseStream handler to flip the `playing` bit.

### PR DESCRIPTION
**Pull request by ArtemGr**
The `playing` variable was miscarried in wasapi, resulting in it rejecting to resume a stream.

### CODE REVIEW

**Comment by mitchmindtree** [comment]
Thanks! Would you mind also adding this fix to the CHANGELOG?

**Comment by ArtemGr** [comment]
You're welcome. Added the Changelog entry.

> that was probably quite annoying to investigate.

Not at all, did spot it almost at a first glance, that part of the code was apparently quite readable and not overdesigned, thank you.

**Comment by ArtemGr** [comment]
Should I go ahead and bump the Cargo version too?

**Comment by tomaka** [comment]
The changelog entry should be added to the `Unreleased` section.
But if you want, you can bump the Cargo version 0.8.2 and adjust the changelog appropriately.

**Comment by ArtemGr** [comment]
Moved and merged. Sorry for the hiccups.

**Pull request merged**
