### PR TITLE
Add coreaudio-rs dependency for i686-apple-darwin

### PR DESCRIPTION
**Pull request by yupferris**
Fixes build for 32-bit mac. Tested locally in both configs, works just fine!

Also, can I request a minor release be published after merge? Would be nice to use this ASAP :) Thanks!

### CODE REVIEW

**Comment by yupferris** [comment]
This is likely all that's needed to get rodio working for this target as well, though I haven't tested that specifically.

**Comment by tomaka** [comment]
> Also, can I request a minor release be published after merge? Would be nice to use this ASAP :) Thanks!

Just modify the version number in the Cargo.toml. You can add it to this PR.

**Comment by yupferris** [comment]
Should I update the one in `README.md` as well, or should that one continue to read "0.4.0" ?

**Comment by yupferris** [comment]
ah nvm, I hadn't realized ["0.4.0" would be the same as "^0.4.0" in cargo](http://doc.crates.io/specifying-dependencies.html#specifying-dependencies-from-cratesio). Should be good to go here then with https://github.com/tomaka/cpal/pull/143/commits/6e8f51de09ebb45489d741262dfdf5255d853a1e :)

**Pull request merged**
