### PR TITLE
Fix for loop in EventLoop::run optimised out in a release build on macOS

### PR DESCRIPTION
**Pull request by shockham**
Fix in relation to #148 with the loop in EventLoop::run optimised out in a release build on macOS, doesn't feel very elegant, so am open to suggestions for something nicer.

### CODE REVIEW

**Comment by jonas-schievink** [comment]
cc https://github.com/rust-lang/rust/issues/28728

**Comment by shockham** [comment]
Added a commit to this which addresses tomaka/rodio#107

**Comment by tomaka** [comment]
I don't know how coreaudio works, but I guess I can merge this anyway?

**Comment by shockham** [comment]
Yeah I think so, just gets things working again

**Comment by tomaka** [comment]
Thanks

**Pull request merged**
