### PR TITLE
Query alsa to determine the sound channels

### PR DESCRIPTION
**Pull request by mvdnes**
Use `alsa::snd_pcm_query_chmaps` to get the available sound channel mappings.

### CODE REVIEW

**Comment by mvdnes** [comment]
The required functions where added in ALSA [1.0.27][version], while Travis unfortunately has 1.0.25.

[version]: http://upstream.rosalinux.ru/compat_reports/alsa/1.0.26_to_1.0.27/abi_compat_report.html

**Comment by mceier** [comment]
Duplicate of: https://github.com/tomaka/cpal/pull/67 :)

**Comment by tomaka** [comment]
And conflicts with #84 

I don't really know how to handle that except by dynamically loading dlopen and dispatching depending on the version.

**Comment by mvdnes** [comment]
Ah I see! Should look through the issues more carefully next time ;)

**Pull request closed without merging**
